# Kubernetes v1.25+
# Base storage configuration for Memorable platform
# Implements encrypted storage classes and persistent volumes with performance optimizations

apiVersion: v1
kind: List
items:
# Storage Classes
- apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    name: memorable-standard
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
  provisioner: kubernetes.io/aws-ebs
  parameters:
    type: gp3
    encrypted: "true"
    kmsKeyId: ${aws_kms_key.storage.arn}
    zone: multi-az
    fsType: ext4
    throughput: "125"
    iops: "3000"
  reclaimPolicy: Retain
  volumeBindingMode: WaitForFirstConsumer
  allowVolumeExpansion: true
  mountOptions:
    - noatime
    - nodiratime

- apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    name: memorable-fast
  provisioner: kubernetes.io/aws-ebs
  parameters:
    type: io2
    iopsPerGB: "10"
    encrypted: "true"
    kmsKeyId: ${aws_kms_key.storage.arn}
    zone: multi-az
    fsType: ext4
  reclaimPolicy: Retain
  volumeBindingMode: WaitForFirstConsumer
  allowVolumeExpansion: true
  mountOptions:
    - noatime
    - nodiratime

# Persistent Volumes
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: book-storage
    labels:
      type: book-data
  spec:
    capacity:
      storage: 100Gi
    storageClassName: memorable-standard
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    volumeMode: Filesystem
    awsElasticBlockStore:
      fsType: ext4
      encrypted: true
      kmsKeyId: ${aws_kms_key.storage.arn}

- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: ai-storage
    labels:
      type: ai-data
  spec:
    capacity:
      storage: 200Gi
    storageClassName: memorable-fast
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    volumeMode: Filesystem
    awsElasticBlockStore:
      fsType: ext4
      encrypted: true
      kmsKeyId: ${aws_kms_key.storage.arn}

# Persistent Volume Claims
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: book-storage-claim
    namespace: memorable-book
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 100Gi
    storageClassName: memorable-standard
    volumeMode: Filesystem

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ai-storage-claim
    namespace: memorable-ai
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 200Gi
    storageClassName: memorable-fast
    volumeMode: Filesystem

# Storage Monitor ConfigMap
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: storage-monitor-config
    namespace: memorable-monitoring
  data:
    encryption-monitoring: |
      enabled: true
      check-interval: 300s
    performance-monitoring: |
      enabled: true
      metrics:
        - iops
        - throughput
        - latency
    capacity-monitoring: |
      enabled: true
      threshold-warning: 80
      threshold-critical: 90